spring:
  datasource:
    username: springtest
    password: springtest
    url: jdbc:postgresql://localhost:5432/springtest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
